name: Triggers
run-name: I am creating some triggers to practice with
on:
  push:
    branches: 
      - 'main'
    paths:
      - '**/.js'
  pull_request:
    types: [opened, reopened]
    branches: 
      - 'main'
    paths:
      - '**/.js'
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types:  [created, deleted]
  workflow_dispatch:
    inputs:
      favorite_language:
        description: 'Favorite language'
        default: JavaScript
        required: true
        type: choice
        options:
        - Python
        - JavaScript
        - PHP
      name:
        description: 'Your name'
        required: true
        default: Martin
        type: string
  schedule:
    - cron:  '15 10,22 * * *'
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir nombre
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV
      - name: Definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hola_lenguaje.py
  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hola_mundo.py
